### ISSUE TITLE
sdk版本

### ISSUE THREAD

**Issue by GK1118** [waimifeier/hikvision-spring-boot-starter#1]
你好，这个对sdk.dll的版本有要求吗，可以给看一下前端如何调用接口吗，开发经验浅薄，这种请求没有使用过

**Comment by waimifeier** [comment]
库文件去海康的官网下载：https://open.hikvision.com/download/5cda567cf47ae80dd41a54b3?type=undefined

**Comment by GK1118** [comment]
前端调用可以给看下吗
